jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false
